# -*- coding: utf-8 -*-
"""DosTel1 _DosTel2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krIGP5jPI3PIhIlPEPJQNY1Fb2597WW9
"""

import pandas as pd

import matplotlib.pyplot as plt

url = ("https://visualization.osdr.nasa.gov/radlab/api/?spacecraft=&module=&instrument=&timestamp=&format=csv&timestamp%3E=2007-07-03T10:26&timestamp%3C=2024-06-17T11:59&instrument_id=DosTel1&absorbed_dose_rate=&")

d = pd.read_csv(url)

print(d)

d['timestamp'] = pd.to_datetime(d['timestamp'])

plt.plot(d['timestamp'] , d['absorbed_dose_rate'])

plt.show()

url2 = ("https://visualization.osdr.nasa.gov/radlab/api/?spacecraft=&module=&instrument=&timestamp=&format=csv&timestamp%3E=2007-07-03T10:26&timestamp%3C=2024-06-17T11:59&instrument_id=DosTel2&absorbed_dose_rate=&")

f = pd.read_csv(url2)

print(f)

f['timestamp'] = pd.to_datetime(f['timestamp'])

plt.plot(f['timestamp'] , f['absorbed_dose_rate'])

plt.show()