# -*- coding: utf-8 -*-
"""Fuel Mass_vs_av (m/s).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLWT3zOjDYCBM72PXf8w8hy8fEAMj64a
"""

import numpy as np
import matplotlib.pyplot as plt

def rocket_delta_v(ve, m0 , mf):
  return  ve*np.log(m0/mf)


ve = 3000
payload_mass = 1000
fuel_masses = np.linspace(100, 5000, 100)

delta_vs= []
for i in fuel_masses :
  a = rocket_delta_v(ve, payload_mass + i , payload_mass)
  delta_vs.append(a)

plt.figure(figsize=(10, 6))
plt.plot(fuel_masses, delta_vs, label=f'Exhaust velocity = {ve} m/s')
plt.title("Tsiolkovsky Rocket Equation: Av vs Fuel Mass")
plt.xlabel ("Fuel Mass (kg)")
plt.ylabel ("av (m/s)")
plt.grid(True)
plt.legend()
plt.show()