# -*- coding: utf-8 -*-
"""Material_Thickness_vs_Transmitted Intensity_10-06-25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpyGE1RigKzDt2lYA-phxpuzMl7vMPr_
"""

import numpy as np
import matplotlib.pyplot as plt

def attenuated_intensity(I0, mu , x):
  return I0*np.exp(-mu * x)

I0 = 1.0
mu = 0.0001
thickness = np.linspace(0, 10 , 100)

intensity = attenuated_intensity(I0, mu , thickness)

plt.plot(thickness, intensity)

# Add labels and title to the plot
plt. xlabel("Material Thickness (cm)")
# Label for the x-axis
plt. ylabel ("Transmitted Intensity")
# Label for the y-axis
plt.title("Exponential Attenuation of EM Radiation in Air") # Plot title
# Display the plot
plt.show()

import numpy as np
import matplotlib.pyplot as plt

def attenuated_intensity(I0, mu, x):
    return I0 * np.exp(-mu * x)

# Define parameters outside the function
I0 = 1
x = np.linspace(0, 10, 500)
materials = {'Air (u = 0.0001)': 0.0001, 'Water (u = 0.2)': 0.2, 'Lead (u = 0.5)': 0.5}

# Loop through materials and plot
for plot_label, mu_val in materials.items():
    I = attenuated_intensity(I0, mu_val, x)
    plt.plot(x, I, label=plot_label)

# Set plot properties after all plots are added
plt.title('Attenuation of X-Rays in Different Materials')
plt.xlabel('Thickness')
plt.ylabel('Transmitted Intensity')
plt.legend()
plt.grid(True) # Added for better readability
plt.show()