# -*- coding: utf-8 -*-
"""np_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BdXaQmzY1RcT-hT2sAhfYX9yB9dFXnGh
"""

import pandas as pd
import numpy as np


import matplotlib.pyplot as plt\

x = np.linspace(0, 2, 100)

a = 2

f = a * np.exp(x)

plt.plot(x,f)

plt.xlabel('x')

plt.xlabel('f(x)')

plt.show()

import numpy as np
import matplotlib.pyplot as plt
energy = np.logspace(0,3,100)
flux = 1e4*energy**(-2.7)
plt.loglog(energy,flux)
plt.title('Flux vs Energy')
plt.xlabel('Energy')
plt.ylabel('Flux')
plt.show()