# -*- coding: utf-8 -*-
"""Scattering angle_vs_Scattered Photon Energy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbIBIlsLjMklx-CcYs3z1dDdoenrCH3i
"""

import numpy as np
import matplotlib.pyplot as plt
incident_energy_kev = 100.0
electron_rest_mass_keV = 511.0
theta_deg = np.linspace(0, 180, 500)
theta_rad = np.radians(theta_deg)

scattered_energy_keV = incident_energy_kev / (1 + (incident_energy_kev/ electron_rest_mass_keV)*(1-np.cos(theta_rad)))

plt.figure(figsize = (9,5))
plt.plot(theta_deg, scattered_energy_keV)

plt.title("Photon Scattering ")
plt.xlabel("Scattering angle")
plt.ylabel("Scattered Photon Energy")