# -*- coding: utf-8 -*-
"""Sunspot_Number_vs_Solar_flares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2soc725lLJXjpUr4dfIAcI7uo-EMxu4

#1. Library Imports
"""

import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

"""#2. Loading Sunspot data"""

# Define column names based on the sample
column_names = ['Year', 'Month', 'Day', 'Decimal_Year', 'Sunspot_Number', 'SD', 'Num_Obs', 'Definitive']

# Read the CSV file with semicolon separator
df = pd.read_csv('/content/Sunspot No.csv', sep=';', header=None, names=column_names)

# Create a proper datetime column
df['Date'] = pd.to_datetime(df[['Year', 'Month', 'Day']])

"""#3. Loading Flare data"""

# Solar flares data
solar_flares_with_flux = [
    {'date': '2010-08-01', 'flux_W_per_m2': 1.0e-05}, # M1.0
    {'date': '2011-02-15', 'flux_W_per_m2': 2.2e-04}, # X2.2
    {'date': '2011-03-07', 'flux_W_per_m2': 5.4e-04}, # X5.4
    {'date': '2011-08-09', 'flux_W_per_m2': 6.9e-04}, # X6.9
    {'date': '2012-01-23', 'flux_W_per_m2': 1.7e-04}, # X1.7
    {'date': '2012-03-06', 'flux_W_per_m2': 5.4e-04}, # X5.4
    {'date': '2012-07-12', 'flux_W_per_m2': 1.4e-04}, # X1.4
    {'date': '2012-07-23', 'flux_W_per_m2': 1.0e-04}, # X1.0
    {'date': '2013-05-13', 'flux_W_per_m2': 2.8e-04}, # X2.8
    {'date': '2013-05-14', 'flux_W_per_m2': 3.2e-04}, # X3.2
    {'date': '2013-10-25', 'flux_W_per_m2': 2.1e-04}, # X2.1
    {'date': '2013-10-28', 'flux_W_per_m2': 1.7e-04}, # X1.7
    {'date': '2013-11-05', 'flux_W_per_m2': 3.3e-04}, # X3.3
    {'date': '2014-02-25', 'flux_W_per_m2': 4.9e-04}, # X4.9
    {'date': '2014-03-29', 'flux_W_per_m2': 1.0e-04}, # X1.0
    {'date': '2014-09-10', 'flux_W_per_m2': 1.6e-04}, # X1.6
    {'date': '2015-03-11', 'flux_W_per_m2': 2.1e-04}, # X2.1
    {'date': '2015-06-21', 'flux_W_per_m2': 2.0e-04}, # X2.0
    {'date': '2017-09-06', 'flux_W_per_m2': 9.3e-04}, # X9.3
    {'date': '2017-09-07', 'flux_W_per_m2': 1.3e-04}, # X1.3
    {'date': '2017-09-10', 'flux_W_per_m2': 8.2e-04}, # X8.2
    {'date': '2017-09-11', 'flux_W_per_m2': 1.2e-04}, # X1.2
    {'date': '2020-11-29', 'flux_W_per_m2': 4.4e-05}  # M4.4
]

# Convert to DataFrame for easier handling
flare_df = pd.DataFrame(solar_flares_with_flux)
flare_df['date'] = pd.to_datetime(flare_df['date'])

"""#4. Plotting the data"""

# Plotting
fig, ax1 = plt.subplots(figsize=(12,6))

# Line plot for sunspot number
ax1.plot(df['Date'], df['Sunspot_Number'], color='orange', label='Sunspot Number')
ax1.set_xlabel('Date')
ax1.set_ylabel('Sunspot Number', color='orange')
ax1.tick_params(axis='y', labelcolor='orange')

# Twin axis for solar flare flux
ax2 = ax1.twinx()
ax2.scatter(flare_df['date'], flare_df['flux_W_per_m2'], color='blue', label='Solar Flare Flux', marker='o')
ax2.set_ylabel('Solar Flare Flux (W/m²)', color='blue')
ax2.set_yscale('log')
ax2.tick_params(axis='y', labelcolor='blue')

# Combine legends
lines_1, labels_1 = ax1.get_legend_handles_labels()
lines_2, labels_2 = ax2.get_legend_handles_labels()
ax1.legend(lines_1 + lines_2, labels_1 + labels_2, loc='upper left')

plt.title('Sunspot Number and Solar Flare Flux Over Time')
plt.show()