# -*- coding: utf-8 -*-
"""Sunspot Number vs Flight Regularity Rate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yC7_S1BBHq2gwnYAvsooxsIbMyXzdU9
"""

import pandas as pd
import matplotlib.pyplot as plt

sunspot_df = pd.read_csv('/content/sunspot_data.csv')
flight_df = pd.read_csv('/content/flight_data.csv')

years = sunspot_df['Year']
sunspot_values = sunspot_df['Sunspot_Number']
flight_values = flight_df['Flight_Punctuality']

fig, ax1 = plt.subplots(figsize=(12, 6))

width = 0.4

ax1.bar(years- width/2 , sunspot_values, width=width, color='blue', label='Sunspot Number')
ax1.set_ylabel('Yearly Mean Total Sunspot Number', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')
ax1.set_xlabel('Year')


ax2 = ax1.twinx()
ax2.bar(years + width/2 , flight_values, width=width, color='red', label='Flight Regularity Rate')
ax2.plot(years, flight_values, color='red', linewidth=2, marker='o')
ax2.set_ylabel('Yearly Mean Flight Punctuality Rate (%)', color='red')
ax2.tick_params(axis='y', labelcolor='red')
ax2.set_ylim(60, 90)

plt.title('Sunspot Number vs Flight Regularity Rate', color='red')

plt.show()