# -*- coding: utf-8 -*-
"""Sunspot_No_vs_Geomagnetic_Storms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPeR5X6gr8GL729Qbh0mh5fo_JuJXDmC

#1. Library Imports
"""

import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

"""#2. Loading Sunspot data"""

# Define column names based on the sample
column_names = ['Year', 'Month', 'Day', 'Decimal_Year', 'Sunspot_Number', 'SD', 'Num_Obs', 'Definitive']

# Read the CSV file with semicolon separator
df = pd.read_csv('/content/Sunspot No.csv', sep=';', header=None, names=column_names)

# Create a proper datetime column
df['Date'] = pd.to_datetime(df[['Year', 'Month', 'Day']])

"""#3. Loading Flare data


"""

strong_geomagnetic_storm_dates_2010_2020_with_kp = [
    {'date': '2011-08-05', 'kp_index': 6},
    {'date': '2011-09-26', 'kp_index': 6},
    {'date': '2011-10-24', 'kp_index': 6},
    {'date': '2012-01-22', 'kp_index': 5},
    {'date': '2012-03-08', 'kp_index': 7},
    {'date': '2012-07-15', 'kp_index': 7},
    {'date': '2012-09-27', 'kp_index': 6},
    {'date': '2013-03-17', 'kp_index': 6},
    {'date': '2013-05-31', 'kp_index': 6},
    {'date': '2013-10-09', 'kp_index': 6},
    {'date': '2013-10-31', 'kp_index': 7},
    {'date': '2014-02-18', 'kp_index': 6},
    {'date': '2014-09-12', 'kp_index': 6},
    {'date': '2015-03-17', 'kp_index': 8},
    {'date': '2015-06-22', 'kp_index': 8},
    {'date': '2015-08-16', 'kp_index': 7},
    {'date': '2016-06-03', 'kp_index': 6},
    {'date': '2016-10-13', 'kp_index': 6},
    {'date': '2017-03-27', 'kp_index': 6},
    {'date': '2017-05-27', 'kp_index': 7},
    {'date': '2017-09-07', 'kp_index': 8},
    {'date': '2017-09-28', 'kp_index': 6},
    {'date': '2018-08-26', 'kp_index': 7}
]

kp_df = pd.DataFrame(strong_geomagnetic_storm_dates_2010_2020_with_kp)
kp_df['date'] = pd.to_datetime(kp_df['date'])

"""#4. Plotting the data

"""

# Plotting
fig, ax1 = plt.subplots(figsize=(12,6))

# Line plot for sunspot number
ax1.plot(df['Date'], df['Sunspot_Number'], color='orange', label='Sunspot Number')
ax1.set_xlabel('Date')
ax1.set_ylabel('Sunspot Number', color='orange')
ax1.tick_params(axis='y', labelcolor='orange')

# Twin axis for Kp index
ax2 = ax1.twinx()
ax2.scatter(kp_df['date'], kp_df['kp_index'], color='crimson', label='Kp Index (Storms)', zorder=10)
ax2.set_ylabel('Kp Index', color='crimson')
ax2.tick_params(axis='y', labelcolor='crimson')

# Combine legends
lines_1, labels_1 = ax1.get_legend_handles_labels()
lines_2, labels_2 = ax2.get_legend_handles_labels()
ax1.legend(lines_1 + lines_2, labels_1 + labels_2, loc='upper left')

plt.title('Sunspot Number and Solar Flare Flux Over Time')
plt.show()