# -*- coding: utf-8 -*-
"""Sunspots_vs_Time_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1As9edDAc6KAhhikb3v-984sjzBd4BL93

# 1. LIBRARY IMPORTS
"""

# === 1. LIBRARY IMPORTS ===
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import requests
from io import StringIO

"""#  2.  Load daily sunspot data from SILSO (Royal Observatory of Belgium)."""

url = "https://www.sidc.be/silso/INFO/sndtotcsv.php"  # Link to the real CSV data
response = requests.get(url)  # Make an HTTP GET request
response.raise_for_status()  # Raise an error if the request failed

# Read CSV using pandas with appropriate headers and separator
data = pd.read_csv(StringIO(response.text), sep=';', header=None,
                    names=['Year', 'Month', 'Day', 'Date_fraction',
                            'Sunspot_number', 'Std_dev', 'Observations', 'Flag'])

print(data)

"""#3. Data Filtering"""

# Create a datetime column from year, month, day
data['Date'] = pd.to_datetime(data[['Year', 'Month', 'Day']])

start_year = 1950
end_year=2025
filtered_data = data[(data['Year'] >= start_year) & (data['Year'] <= end_year)].copy()
filtered_data = filtered_data.sort_values('Date')

print(f" {len(filtered_data):,} daily observations ")

"""# 4. PLOT DAILY DATA FUNCTION


"""

plt.figure(figsize=(18, 10))
plt.plot(filtered_data['Date'], filtered_data['Sunspot_number'],
          linewidth=0.5, alpha=0.7, color='blue', label='Daily Sunspot Count')

# Titles and labels
plt.title(f'Daily Sunspot Numbers: Modern Space Age ({start_year}-{end_year})', fontsize=16, fontweight='bold')
plt.xlabel('Year', fontsize=14)
plt.ylabel('Daily Sunspot Number', fontsize=14)

plt.legend(fontsize=11, loc='upper right')

plt.show()