# -*- coding: utf-8 -*-
"""Sunspot_Butterfly_Diagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoZRjVwl2GMrnm8fv6hGn8xOeNxDM5KX
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as colors

df = pd .read_csv("/content/sunspot_area.csv")

df["Date"] = pd.to_datetime(df["Date"], errors = "coerce")

start_year = 1940
end_year = 2021
df = df[(df["Date"].dt.year >= start_year) & (df["Date"].dt.year <= end_year)]

norm = colors.Normalize(vmin=0, vmax=2000)

plt.figure(figsize=(14, 6))
sc = plt.scatter(df["Date"], df["Lat"], c=df["Area"], cmap="hot", s=10, alpha=0.7, norm=norm)
plt.colorbar(sc, label="Sunspot Area (µHem)")
plt.xlabel("Date")
plt.ylabel("Latitude (°)")
plt.title("Sunspot Butterfly Diagram")
plt.grid(True)
plt.show()

df = df[df["Area"] > 0]
df["Area_percent"] = df["Area"] / 10000  # Since 1,000,000 µHem = 100%

plt.figure(figsize=(12, 5))
plt.plot(df["Date"], df["Area_percent"], color="black", linewidth=1)
plt.xlabel("Date")
plt.ylabel("Sunspot Area (% of Visible Hemisphere)")
plt.title("Average Daily Sunspot Area")
plt.grid(True)

plt.show()