# -*- coding: utf-8 -*-
"""timestamp_vs_dose_rate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doZa9ciKQFjHh72Xzr__JKBUZMIRC0VZ
"""

import pandas as pd
import matplotlib.pyplot as plt

d = pd.read_csv('/content/Dose_iss.csv')

print(d)

d['timestamp'] = pd.to_datetime(d['timestamp'])
plt.plot(d['timestamp'],d['absorbed_dose_rate'])

import pandas as pd
f= pd.read_csv('/content/Flux_iss.csv')

print(f)

f['timestamp'] = pd.to_datetime(f['timestamp'])
plt.figure(figsize = (10,6))
plt.plot(f['timestamp'],f['flux'])
plt.xlabel('Time' , fontsize = 12)
plt.ylabel('Flux' , fontsize = 12)
plt.title('Flux vs Time' , fontsize=14)
plt.show()